# Generated by Django 3.1.3 on 2020-12-31 09:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_email',
        ),
        migrations.AddField(
            model_name='product',
            name='product_address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_bdate',
            field=models.DateField(null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_email',
            field=models.EmailField(max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
