# Generated by Django 3.1.3 on 2020-12-14 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20201215_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
