# Generated by Django 3.1.3 on 2020-12-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201215_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
