# Generated by Django 3.1.1 on 2021-01-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210117_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productOnwer_bdate',
        ),
    ]
