# Generated by Django 3.1.1 on 2021-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210122_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bdate',
            field=models.DateField(null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='product',
            name='productOnwer_bdate',
            field=models.DateField(null=True, verbose_name='Birthdate'),
        ),
    ]
