# Generated by Django 3.1.1 on 2021-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20210125_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
